name: Zig embedded

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets:
          - aarch64-linux-gnu
          - aarch64-linux
          - riscv64-linux-musl
          - powerpc64-linux
          - aarch64-windows

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - name: Build Summary ${{ matrix.targets }}
        run: zig build --summary all -freference-trace -Dtarget=${{ matrix.targets }}
